name: kidronband
favicon: null
layout_spectrum: 0.10825393255800009
typography_spectrum: 0.14240862289443612
title: The Official Site of Kidron
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#ffffff'
    - '#444854'
    - '#6d705f'
    - '#dbad94'
  brandStrength: 0.25
  lightness: 0.6917795350309461
  saturation: 0.7621828708797693
  rhythmicContrast: 0.444313159910962
purpose: []
